name: SonarCloud Scan
description: >
  For testing. Do not use this GitHub Action. Use the `sonarqube-scan-action` instead.
runs:
  using: "composite"
  steps:
    - name: Fail
      shell: bash
      run: exit 1